### ISSUE TITLE
"specified key not present"

### ISSUE THREAD

**Issue by BenATemple** [open-ephys/open-ephys-matlab-tools#2]
Hi, 
When I try to load data that was recorded using the new GUI (v.0.6.0) into Matlab, I encounter the following error:
-I set my directory
-I enter season = Session(directory)
-But then I receive an error:
"Error using containers.Map/subsref
The specified key is not present in this container."
Thanks for any help or ideas!
Ben

**Comment by medengineer** [comment]
Hi,

Are you using the 0.6.0 branch of the matlab-tools? 
Which data format did you use for recording? 

Pavel

**Comment by BenATemple** [comment]
Hi there,
Yeah I'm using the 0.6.0 branch.
I recorded in binary (actually this is for some reason the only option that the GUI shows me, but it's what I prefer to record in anyway).
I'm in Matlab 2020a
Thanks for your help!
Ben

**Comment by medengineer** [comment]
Do you get the same error with the pkulik/dev branch?

**Comment by BenATemple** [comment]
Yes, just tried it, same issue sorry.

**Comment by medengineer** [comment]
Okay, can you send me an e-mail at pavel@open-ephys.org and we can continue troubleshooting.

**Comment by medengineer** [comment]
Fixed w/ commit 58f2697
