### ISSUE TITLE
The specified key is not present

### ISSUE THREAD

**Issue by guilhemibos** [open-ephys/open-ephys-matlab-tools#4]
Hi

I've runned into an error which has been raised before about the absence of a key. 
My set up is
data recorded with oe6.+, 
toolbox: open-ephys-matlab-tools-1.0.2
matlab version: 2020a

Error using containers.Map/subsref
The specified key is not present in this container.

Error in BinaryRecording/loadContinuous (line 93)
                stream.metadata.startTimestamp = syncMessages(streamKey);

Error in BinaryRecording (line 40)
            self = self.loadContinuous();

Error in BinaryRecording.detectRecordings (line 254)
                    recordings{end+1} = BinaryRecording(recordingDirectories{recIdx}, expIdx, recIdx);

Error in RecordNode/detectRecordings (line 95)
                self.recordings = BinaryRecording.detectRecordings(self.directory);

Error in RecordNode (line 71)
            self.detectRecordings();

Error in Session/detectRecordNodes (line 70)
                self.recordNodes{end+1} = RecordNode(paths{i});

Error in Session (line 61)
            self.detectRecordNodes();

Thanks
G

**Comment by medengineer** [comment]
Hi

Can you print the value of the streamKey variable in BinaryRecording/loadContinuous (line 93) right before this fails?

**Comment by priyanka-cshl** [comment]
Hello,
I received the same error when trying to load data. 
streamKey = 'Acquisition_Board-100.Rhythm Data'

This used to work just fine for me on an older install so I rolled back to an older version and checked - it works just fine with the version committed 10/04/2022.

**Comment by medengineer** [comment]
Fixed in v1.3.0
