### ISSUE TITLE
Issue Running Session

### ISSUE THREAD

**Issue by crewl2** [open-ephys/open-ephys-matlab-tools#7]
session = Session(directory)

directory =

    '/Volumes/Elements/2021-07-09_10-24-33_Ma_1163_male_placepref'

Searching directory:  /Volumes/Elements/2021-07-09_10-24-33_Ma_1163_male_placepref 
Found recording format: Binary 
Error using readNPYheader
File not found: /Volumes/Elements/2021-07-09_10-24-33_Ma_1163_male_placepref/Record Node
109/experiment1/recording1/continuous/Rhythm_FPGA-100.0/sample_numbers.npy

Error in readNPY (line 9)
    [shape, dataType, fortranOrder, littleEndian, totalHeaderLength, ~] = readNPYheader(filename);

Error in BinaryRecording/loadContinuous (line 81)
                stream.sampleNumbers = readNPY(fullfile(directory, 'sample_numbers.npy'));

Error in BinaryRecording (line 40)
            self = self.loadContinuous();

Error in BinaryRecording.detectRecordings (line 254)
                    recordings{end+1} = BinaryRecording(recordingDirectories{recIdx}, expIdx, recIdx);

Error in RecordNode/detectRecordings (line 95)
                self.recordings = BinaryRecording.detectRecordings(self.directory);

Error in RecordNode (line 71)
            self.detectRecordings();

Error in Session/detectRecordNodes (line 70)
                self.recordNodes{end+1} = RecordNode(paths{i});

Error in Session (line 61)
            self.detectRecordNodes();
 
>> session = Session(directory)
Searching directory:  /Volumes/Elements/2021-07-09_10-24-33_Ma_1163_male_placepref 
Found recording format: OpenEphys 
Error using memmapfile/hCreateMap
File "/Volumes/Elements/2021-07-09_10-24-33_Ma_1163_male_placepref/Record Node 103/all_channels.events" is not large enough to map
with the current format, offset, and repeat values.

Error in indexing (line 794)
                    hCreateMap(obj);

Error in OpenEphysRecording.detectRecordings (line 564)
                        timestamps = timestamps.Data(1:2:end);

Error in RecordNode/detectRecordings (line 97)
                self.recordings = OpenEphysRecording.detectRecordings(self.directory);

Error in RecordNode (line 71)
            self.detectRecordings();

Error in Session/detectRecordNodes (line 70)
                self.recordNodes{end+1} = RecordNode(paths{i});

Error in Session (line 61)
            self.detectRecordNodes();

Don't know why I don't have sample_numbers.npy or why all_channels.events is not large enough.

**Comment by medengineer** [comment]
This issue now being tracked in #8
